### PR TITLE
use markdown-it to replace marked

### PR DESCRIPTION
**Pull request by ghost**
[markdown-it](https://github.com/markdown-it/markdown-it) has many extensions. By using markdown-it, we can support katex and highlight directly without writing our own parsers which are unsound. For example, multiline formula is now supported.
image

### CODE REVIEW

**Comment by lin714093880** [comment]
Looks good @darkflames

**Comment by lin-toto** [comment]
Looks good @dark-flames

**Comment by moesoha** [comment]
@TitanSnow An awesome solution!

**Comment by ghost** [comment]
4a621e0b-64fa-4c93-b996-2848615ac24b

BTW, by using markdown-it, it can support emoji etc. 😄

**Comment by moesoha** [comment]
@TitanSnow Of course. We've already tested markdown-it on Luogu's new front-end. It's really wonderful.

**Pull request merged**
